<a href="https://colab.research.google.com/github/0Thaly/Grafos/blob/main/Trabalho_representa%C3%A7%C3%A3o_de_grafos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Estefane
def criar_grafo_a_partir_de_bytes(dados_binarios):
    # Decodifique os bytes em uma string
    dados_str = dados_binarios.decode('utf-8')

    # Divida a string em linhas
    linhas = dados_str.strip().split('\n')

    # O número de vértices é a primeira linha
    num_vertices = int(linhas[0])

    # atribuindo a quantidade de vértices a uma váriavel globa para ter acesso fora da função
    global nvertices
    nvertices = num_vertices

    # Inicialize o grafo como um dicionário vazio
    grafo = {}

    # Processar as linhas subsequentes para criar as arestas do grafo
    for linha in linhas[1:]:
        partes = linha.split('\t')
        u, v, peso = int(partes[0]), int(partes[1]), float(partes[2])

        if u in grafo:
            grafo[u].append((v, peso))
        else:
            grafo[u] = [(v, peso)]

    return grafo

def ler_grafo_binario(nome_arquivo):
   # Nome do arquivo binário que você deseja ler
  try:
      with open(nome_arquivo, 'rb') as arquivo_binario:
          # Leia o conteúdo do arquivo binário
          dados_binarios = arquivo_binario.read()

          # Faça algo com os dados binários
          return dados_binarios
  except FileNotFoundError:
      print(f'O arquivo {nome_arquivo} não foi encontrado.')
  except Exception as e:
      print(f'Ocorreu um erro ao ler o arquivo: {str(e)}')

def criar_matriz_incidencia(grafo, nvertices):
    # Obtenha a lista de vértices e arestas
    vertices = [x for x in range(1, nvertices + 1)] # lista com os vértices
    arestas = []
    pesos = []
    for u, vizinhos in grafo.items():
        arestas.extend([(u, v) for (v, _) in vizinhos]) # lista com as arestas
        pesos.extend([p for (_, p) in vizinhos]) # listas com os pesos
    print(arestas)
    # Crie a matriz de incidência com zeros
    num_vertices = len(vertices)
    num_arestas = len(arestas)
    matriz_incidencia = [[0] * num_vertices for _ in range(num_arestas)] # vertices * arestas

    # Preencha a matriz de incidência
    for j, (v1, v2) in enumerate(arestas): # percorrendo as arestas da matriz/linhas
            matriz_incidencia[j][v1-1] = pesos[j] # linha j - vertice origem =  peso
            matriz_incidencia[j][v2-1] = -pesos[j]  # linha j = vertice  destino = - peso
    return matriz_incidencia

# Exemplo de uso
nome_arquivo = 'inst-13' # instância do grafo / arquivo externo
grafo_lido = ler_grafo_binario(nome_arquivo)
grafo_gerado = criar_grafo_a_partir_de_bytes(grafo_lido) # grafo gerado à partir do arquivo

# Exiba a representação do grafo
print('Grafo: \n')
for vertice, arestas in grafo_gerado.items():
    print(f'Vértice {vertice}:')
    for (vizinho, peso) in arestas:
        print(f'  -> Vizinho: {vizinho}, Peso: {peso}')

# criando matriz de incidência
matriz_incidencia = criar_matriz_incidencia(grafo_gerado, nvertices)

print('\n Matriz de incidência: \n')
# Exibir matriz de incidência
for index, linha in enumerate(matriz_incidencia):
    print(f'0{index+1} - {linha}') if len(str(index + 1)) < 2 else print(f'{index+1} - {linha}')

Grafo: 

Vértice 1:
  -> Vizinho: 2, Peso: 1.0
  -> Vizinho: 8, Peso: 1.0
  -> Vizinho: 11, Peso: 1.0
  -> Vizinho: 12, Peso: 1.0
Vértice 2:
  -> Vizinho: 3, Peso: 1.0
  -> Vizinho: 4, Peso: 1.0
  -> Vizinho: 5, Peso: 1.0
  -> Vizinho: 7, Peso: 1.0
Vértice 8:
  -> Vizinho: 10, Peso: 1.0
  -> Vizinho: 7, Peso: 1.0
Vértice 11:
  -> Vizinho: 12, Peso: 1.0
Vértice 3:
  -> Vizinho: 4, Peso: 1.0
Vértice 7:
  -> Vizinho: 6, Peso: 1.0
  -> Vizinho: 9, Peso: 1.0
Vértice 10:
  -> Vizinho: 9, Peso: 1.0
Vértice 6:
  -> Vizinho: 5, Peso: 1.0
[(1, 2), (1, 8), (1, 11), (1, 12), (2, 3), (2, 4), (2, 5), (2, 7), (8, 10), (8, 7), (11, 12), (3, 4), (7, 6), (7, 9), (10, 9), (6, 5)]

 Matriz de incidência: 

01 - [1.0, -1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
02 - [1.0, 0, 0, 0, 0, 0, 0, -1.0, 0, 0, 0, 0, 0]
03 - [1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1.0, 0, 0]
04 - [1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1.0, 0]
05 - [0, 1.0, -1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
06 - [0, 1.0, 0, -1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
07 -

In [ ]:

#Thalita Reis

def matriz_incidencia(grafo, num_vertices):
    # Inicialize a matriz de incidência com zeros
    matriz = [[0] * num_vertices for _ in range(len(grafo))]

    # Preencha a matriz de incidência com base nas arestas do grafo
    for i, aresta in enumerate(grafo):
        v1, v2, peso = aresta
        # Marque a posição correspondente na matriz como 1 para v1
        matriz[i][v1 - 1] = 1
        # Marque a posição correspondente na matriz como -1 para v2
        matriz[i][v2 - 1] = -1

    return matriz

# Número de vértices no grafo
num_vertices = 9

# Lista de arestas com formato (v1, v2, peso)
grafo = [
    (1, 2, 4),
    (1, 8, 8),
    (2, 3, 8),
    (2, 8, 11),
    (3, 4, 7),


]

# Obtenha a matriz de incidência
matriz = matriz_incidencia(grafo, num_vertices)

# Imprima a matriz de incidência
for linha in matriz:
    print(linha)

[1, -1, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, -1, 0]
[0, 1, -1, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, -1, 0]
[0, 0, 1, -1, 0, 0, 0, 0, 0]


Dados binários lidos: b'9\n1\t2\t4\n1\t8\t8\n2\t3\t8\n2\t8\t11\n3\t4\t7\n3\t9\t2\n3\t6\t4\n4\t5\t9\n4\t6\t14\n5\t6\t10\n6\t7\t2\n7\t9\t6\n7\t8\t1\n9\t8\t7\n\n\n'


In [ ]:
#teste thainara
# Importe as bibliotecas necessárias
import numpy as np

# Nome do arquivo .g
nome_arquivo = "inst-13.txt"

# Leitura do arquivo
with open(nome_arquivo, "r") as arquivo:
    linhas = arquivo.readlines()

# Procure pela linha que começa com "p edges" para obter o número de vértices e arestas
for linha in linhas:
    if linha.startswith("p edges"):
        partes = linha.strip().split()
        num_vertices = int(partes[2])
        num_arestas = int(partes[3])
        break

# Inicialize a matriz de incidência com zeros
matriz_incidencia = np.zeros((num_vertices, num_arestas), dtype=int)

# Percorra as linhas que começam com "e" para preencher a matriz de incidência
for linha in linhas:
    if linha.startswith("e"):
        partes = linha.strip().split()
        vertice_origem = int(partes[1]) - 1  # Subtrai 1 para ajustar ao índice baseado em zero
        vertice_destino = int(partes[2]) - 1
        matriz_incidencia[vertice_origem][vertice_destino] = 1

# Imprima a matriz de incidência
print(matriz_incidencia)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [ ]:
#Copia Estefane
nvertices = 0
# Função para decodificar os bytes e criar a representação do grafo
def criar_grafo_a_partir_de_bytes(dados_binarios):
    global nvertices
    # Decodifique os bytes em uma string
    dados_str = dados_binarios.decode('utf-8')

    # Divida a string em linhas
    linhas = dados_str.strip().split('\n')

    # O número de vértices é a primeira linha
    num_vertices = int(linhas[0])
    nvertices = num_vertices

    # Inicialize o grafo como um dicionário vazio
    grafo = {}

    # Processar as linhas subsequentes para criar as arestas do grafo
    for linha in linhas[1:]:
        partes = linha.split('\t')
        u, v, peso = int(partes[0]), int(partes[1]), float(partes[2])

        if u in grafo:
            grafo[u].append((v, peso))
        else:
            grafo[u] = [(v, peso)]

    return grafo

def ler_grafo_binario(nome_arquivo):
   # Nome do arquivo binário que você deseja ler
  try:
      with open(nome_arquivo, 'rb') as arquivo_binario:
          # Leia o conteúdo do arquivo binário
          dados_binarios = arquivo_binario.read()

          # Faça algo com os dados binários
          return dados_binarios
  except FileNotFoundError:
      print(f'O arquivo {nome_arquivo} não foi encontrado.')
  except Exception as e:
      print(f'Ocorreu um erro ao ler o arquivo: {str(e)}')

def criar_matriz_incidencia(grafo):
    # Obtenha a lista de vértices e arestas
    vertices = list(grafo.keys())
    arestas = []
    for u, vizinhos in grafo.items():
        arestas.extend([(u, v) for (v, _) in vizinhos])

    # Crie a matriz de incidência com zeros
    num_vertices = len(vertices)
    num_arestas = len(arestas)
    matriz_incidencia = [[0] * num_arestas for _ in range(num_vertices)]

    # Preencha a matriz de incidência
    for i, u in enumerate(vertices):
        for j, (v, _) in enumerate(arestas):
            if u == v:
                matriz_incidencia[i][j] = 2  # Representa um laço (u == v)
            elif u == vertices[i]:
                matriz_incidencia[i][j] = -1  # Representa que o vértice u é o ponto inicial da aresta
            elif v == vertices[i]:
                matriz_incidencia[i][j] = 1  # Representa que o vértice u é o ponto final da aresta
            else:
                matriz_incidencia[i][j] = 0  # Representa a ausência de incidência

    return matriz_incidencia


# Exemplo de uso
nome_arquivo = 'inst-13' # instância do grafo
grafo_lido = ler_grafo_binario(nome_arquivo)
grafo_gerado = criar_grafo_a_partir_de_bytes(grafo_lido) # grafo gerado à partir do arquivo
print(grafo_gerado)

# Exiba a representação do grafo
print('Grafo: \n')
for vertice, arestas in grafo_gerado.items():
    print(f'Vértice {vertice}:')
    for (vizinho, peso) in arestas:
        print(f'  -> Vizinho: {vizinho}, Peso: {peso}')

# criando matriz de incidência
matriz_incidencia = criar_matriz_incidencia(grafo_gerado)

print('\n Matriz de incidência: \n')
# Exibir matriz de incidência
for linha in matriz_incidencia:
    print(linha)



{1: [(2, 1.0), (8, 1.0), (11, 1.0), (12, 1.0)], 2: [(3, 1.0), (4, 1.0), (5, 1.0), (7, 1.0)], 8: [(10, 1.0), (7, 1.0)], 11: [(12, 1.0)], 3: [(4, 1.0)], 7: [(6, 1.0), (9, 1.0)], 10: [(9, 1.0)], 6: [(5, 1.0)]}
Grafo: 

Vértice 1:
  -> Vizinho: 2, Peso: 1.0
  -> Vizinho: 8, Peso: 1.0
  -> Vizinho: 11, Peso: 1.0
  -> Vizinho: 12, Peso: 1.0
Vértice 2:
  -> Vizinho: 3, Peso: 1.0
  -> Vizinho: 4, Peso: 1.0
  -> Vizinho: 5, Peso: 1.0
  -> Vizinho: 7, Peso: 1.0
Vértice 8:
  -> Vizinho: 10, Peso: 1.0
  -> Vizinho: 7, Peso: 1.0
Vértice 11:
  -> Vizinho: 12, Peso: 1.0
Vértice 3:
  -> Vizinho: 4, Peso: 1.0
Vértice 7:
  -> Vizinho: 6, Peso: 1.0
  -> Vizinho: 9, Peso: 1.0
Vértice 10:
  -> Vizinho: 9, Peso: 1.0
Vértice 6:
  -> Vizinho: 5, Peso: 1.0

 Matriz de incidência: 

[2, 2, 2, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
[-1, -1, -1, -1, 2, 2, 2, 2, -1, -1, -1, -1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1, -1, -1, -1, 2, 2, -1, -1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 2, -1,